# Generated by Django 6.0.3 on 2026-04-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking.parkinglot'),
        ),
    ]
