# Generated by Django 6.0.3 on 2026-04-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parkingsession_spot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingsession',
            name='created_at',
        ),
    ]
