# Generated by Django 6.0.3 on 2026-04-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_remove_parkingsession_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingsession',
            old_name='spot',
            new_name='lot',
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to='parking.parkinglot'),
        ),
    ]
