# Generated by Django 6.0.3 on 2026-04-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_rename_parkingsession_spot_to_lot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
    ]
